=== hoakbuilds/playground-trading/ops/default/bridge_module_config_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "mode": {
        "type": "string"
      },
      "bridge": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "module_name": {
            "type": "string"
          },
          "flows": {
            "type": "array",
            "items": [
              {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "source": {
                    "type": "object",
                    "properties": {
                      "module_name": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "key": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "module_name",
                      "name",
                      "key"
                    ]
                  },
                  "target": {
                    "type": "object",
                    "properties": {
                      "module_name": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "key": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "module_name",
                      "name",
                      "key"
                    ]
                  }
                },
                "required": [
                  "name",
                  "source",
                  "target"
                ]
              }
            ]
          },
          "websocket_ip": {
            "type": "string"
          },
          "websocket_port": {
            "type": "integer"
          } 
        },
        "required": [
          "name",
          "module_name",
          "flows",
          "websocket_ip",
          "websocket_port"
        ]
      },
      "api": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "rest_ip": {
            "type": "string"
          },
          "rest_port": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "rest_ip",
          "rest_port"
        ]
      }
    },
    "required": [
      "name",
      "mode",
      "bridge",
      "api"
    ]
  }

=== hoakbuilds/playground-trading/ops/dev/bridge-config.json
{
    "name": "Default Bridge Config",
    "mode": "dev",
    "bridge": {
        "name": "BRIDGE",
        "module_name": "bridge",
        "flows": [
            {
                "name": "warehouse-analysis",
                "source": {
                    "module_name": "warehouse",
                    "name": "warehouse-producer",
                    "key": "k3y-h3r3-w4r3h0us3-4n4ly515"
                },
                "target": {
                    "module_name": "analysis",
                    "name": "analysis-consumer",
                    "key": "k3y-h3r3-w4r3h0us3-4n4ly515"
                }
            }
        ],
        "websocket_ip": "0.0.0.0",
        "websocket_port": 4000
    },
    "api": {
        "name": "BridgeAPI",
        "rest_ip": "0.0.0.0",
        "rest_port": 4100
    }
}
